#!/system/xbin/bash
# Nice Tweaks
# Nuclearmistake, PrimeDirective and Sonicxml

getprio()
{
    awk '{print $19}' /proc/$1/stat
}
getioprio()
{
    ionice $1 | cut -d ' ' -f 4,7
}
smartrenice()
{
    for pid in `pgrep -f $1`; do
        prio=`getprio $pid`
        if [ $prio -ne $2 ]; then
            echo "RENICING $1 from $prio to $2"
            busybox renice $2 $pid 2>&1
        fi
    done
    return 0
}
smartionice()
{
    for pid in `pgrep -f $1`; do
        prio="`getioprio $pid`"
        if [ ! "$prio" = "$2 $3" ]; then
            echo "IONICING $1 to $2 $3"
            ionice $pid $2 $3
         fi
    done
    return 0
}
for kb in "android.inputmethod.latin" "pckeyboard" "swype" "swiftkey"; do smartrenice $kb -13; done
for browser in "dolphin" "com.android.browser" "chrome"; do smartrenice $browser -12; done
smartrenice launcher -13
smartrenice com.android.systemui -12
smartrenice com.google.android.googlequicksearchbox -11
smartrenice com.android.phone -10
smartionice com.android.gallery be 0
smartionice com.google.android.music rt 1
exit 0
