#!/system/bin/sh
# PrimeDirective, Sonicxml, DHO, Nuclearmistake, aosp
# With inspiration from DroidTh3ory

#
# Enable Sysctl Tweaks
#
sysctl -p /system/etc/sysctl.conf

#
# General Queue Tweaks
#
for i in /sys/block/*/queue; do
  echo 512 > $i/nr_requests;
  echo 2 > $i/rq_affinity;
  echo 0 > $i/nomerges;
  echo 0 > $i/add_random;
  echo 0 > $i/rotational;
done;

# kill iostats hardbad
for i in `find /sys/devices/platform -name iostats`; do echo "0" > $i; done
