#!/bin/bash
#
# Squish a exodus otapackage for distribution
# credit for original version: CM
#
EXODUS_PRODUCT="exodus"

export ANDROID_BUILD_TOP=$ANDROID_BUILD_TOP

. $ANDROID_BUILD_TOP/vendor/exodus/tools/functions

if [ -z "$OUT" -o ! -d "$OUT" ]; then
    echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
    exit 1
fi

OTAPACKAGE=$OTA_PACKAGE_PATH

if [ ! -f "$OTAPACKAGE" ]; then
    echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
    exit 1
fi

# Determine what to name the new signed package
MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $OUT/system/build.prop`
OUTVERSION="$TARGET_PRODUCT"_"$MODVERSION"
OUTFILE=$OUT/$OUTVERSION.zip

mv $OTAPACKAGE $OUTFILE

# Create a md5 checksum image of the repacked package
(

img=`basename $OUTFILE`
cd `dirname $OUTFILE`
STRING=$OTA_PACKAGE_PATH
$MD5 $img >$img.md5

ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
echo -e $CL_GRN"================"$CL_RST $EXODUS_PRODUCT-$TARGET_BUILD_VARIANT: $CL_RED"completed"$CL_RST $CL_GRN"================"$CL_RST
echo ""
echo -e $CL_BLU"Product name:"$CL_RST $OUTVERSION.zip
echo -e $CL_BLU"Package Size: "$CL_YLW"$ZIPSIZE     "
echo -e $CL_BLU"md5:"$CL_RST $CL_YLW" $(cat $img.md5 | awk '{ print $1 }')"$CL_RST
echo -e $CL_BLU"Target location:"$CL_RST
echo -e $CL_YLW $OUTFILE $CL_RST
echo ""
echo ""
)

exit 0
